"use client";
import {useEffect,useMemo,useState} from "react";
import {LayoutDashboard,ShoppingBag,Box,ShoppingCart,Users,Wallet,Plus,Search,Menu,X,TrendingUp,CreditCard,Clock3,PackagePlus,ChevronDown} from "lucide-react";
type Sale={id:number,date:string,client:string,product:string,volume:string,total:number,paid:number,status:string};
type Product={id:number,name:string,brand:string,category:string,stock:number,min:number,cost:number};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const initialSales:Sale[]=[];
const initialProducts:Product[]=[];
const clients:{n:string,p:string,o:number,t:number}[]=[];
const purchases:{date:string,supplier:string,item:string,qty:number,total:number,status:string}[]=[];
const nav=[["dashboard","Visão geral",LayoutDashboard],["sales","Vendas",ShoppingBag],["stock","Estoque",Box],["purchases","Compras",ShoppingCart],["clients","Clientes",Users],["finance","Financeiro",Wallet]] as const;
export default function Home(){const[page,setPage]=useState("dashboard"),[mobile,setMobile]=useState(false),[modal,setModal]=useState(false),[query,setQuery]=useState(""),[sales,setSales]=useState(initialSales),[products,setProducts]=useState(initialProducts);useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("daf-splits")||"null");if(x){setSales(x.sales);setProducts(x.products)}}catch{}},[]);useEffect(()=>{localStorage.setItem("daf-splits",JSON.stringify({sales,products}))},[sales,products]);const totals=useMemo(()=>{const gross=sales.reduce((a,s)=>a+s.total,0),received=sales.reduce((a,s)=>a+s.paid,0);return{gross,received,due:gross-received}},[sales]);const title=nav.find(x=>x[0]===page)?.[1];return <div className="shell"><aside className={mobile?"side open":"side"}><div className="brand"><i>D</i><div><b>DAF SPLITS</b><small>GESTÃO</small></div><button onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?"active":""} onClick={()=>{setPage(id);setMobile(false)}}><Icon/>{label}</button>)}</nav><footer><i>FC</i><span><b>Fábio Cruz</b><small>Administrador</small></span></footer></aside><main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div><small>PAINEL ADMINISTRATIVO</small><h1>{title}</h1></div><button className="primary" onClick={()=>setModal(true)}><Plus/> {page==="stock"?"Novo produto":page==="purchases"?"Nova compra":page==="clients"?"Novo cliente":"Nova venda"}</button></header><div className="content">{page==="dashboard"&&<Dashboard sales={sales} products={products} totals={totals} go={setPage}/>} {page==="sales"&&<Sales sales={sales} query={query} setQuery={setQuery}/>} {page==="stock"&&<Stock products={products} query={query} setQuery={setQuery}/>} {page==="purchases"&&<Purchases/>}{page==="clients"&&<Clients query={query} setQuery={setQuery}/>} {page==="finance"&&<Finance sales={sales} totals={totals}/>}</div></main>{modal&&<Modal page={page} close={()=>setModal(false)} addSale={s=>{setSales([s,...sales]);setModal(false)}} addProduct={p=>{setProducts([p,...products]);setModal(false)}}/>}</div>}
function Kpi({label,value,note,Icon,tone}:{label:string,value:string,note:string,Icon:any,tone:string}){return <article className="kpi"><i className={tone}><Icon/></i><div><span>{label}</span><b>{value}</b><small>{note}</small></div></article>}
function Dashboard({sales,products,totals,go}:{sales:Sale[],products:Product[],totals:any,go:(p:string)=>void}){const elapsed=Math.max(1,new Date().getDate()),avg=totals.gross/elapsed,projection=avg*30,days=Array(30).fill(0),max=1;return <><section className="kpis"><Kpi label="Faturamento mensal" value={money(totals.gross)} note="+12,4% vs. mês anterior" Icon={TrendingUp} tone="gold"/><Kpi label="Total recebido" value={money(totals.received)} note={`${Math.round(totals.received/(totals.gross||1)*100)}% do faturamento`} Icon={CreditCard} tone="green"/><Kpi label="A receber" value={money(totals.due)} note={`${sales.filter(s=>s.status!=="Pago").length} pedidos em aberto`} Icon={Clock3} tone="orange"/><Kpi label="Ticket médio" value={money(totals.gross/(sales.length||1))} note={`${sales.length} vendas no período`} Icon={Wallet} tone="blue"/></section><section className="dash"><article className="panel chart"><Title h="Faturamento consolidado + tendência" p="Realizado até hoje e projeção para o restante do mês"/><div className="pills"><span>Média diária <b>{money(avg)}</b></span><span>Projeção mensal <b>{money(projection)}</b></span><span>Meta <b>{money(15000)}</b></span></div><div className="bars">{days.map((v,i)=><div key={i}><i className={i<5?"real":"forecast"} style={{height:`${Math.max(5,v/max*100)}%`}} title={money(v)}/><small>{i+1}</small></div>)}</div><p className="legend"><span>● Realizado</span><span>● Projeção</span></p></article><article className="panel summary"><Title h="Resumo dos pedidos" p="Status dos recebimentos"/><div className="donut" style={{background:`conic-gradient(#cba13a ${totals.received/(totals.gross||1)*100}%,#edf0f3 0)`}}><i><b>{Math.round(totals.received/(totals.gross||1)*100)}%</b><small>recebido</small></i></div>{["Pago","Parcial","Pendente"].map(x=><p key={x}><span>{x}s</span><b>{sales.filter(s=>s.status===x).length}</b></p>)}</article></section><section className="lower"><article className="panel"><Title h="Vendas recentes" p="Últimos pedidos registrados" action="Ver todas" onClick={()=>go("sales")}/><SaleTable sales={sales.slice(0,4)}/></article><article className="panel"><Title h="Atenção no estoque" p="Itens próximos do mínimo" action="Ver estoque" onClick={()=>go("stock")}/><div className="alerts">{products.filter(p=>p.stock<=p.min).map(p=><div key={p.id}><span><b>{p.brand} {p.name}</b><small>{p.stock} ml disponíveis</small></span><em>Estoque baixo</em></div>)}</div></article></section></>}
function Title({h,p,action,onClick}:{h:string,p:string,action?:string,onClick?:()=>void}){return <div className="title"><div><h2>{h}</h2><p>{p}</p></div>{action&&<button onClick={onClick}>{action}</button>}</div>}
function Toolbar({query,setQuery,placeholder}:{query:string,setQuery:(x:string)=>void,placeholder:string}){return <div className="toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label><button>Todos os status <ChevronDown/></button></div>}
function SaleTable({sales}:{sales:Sale[]}){return <div className="table"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Produto</th><th>Total</th><th>Status</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>#{s.id}<small>{s.date}</small></td><td>{s.client}</td><td>{s.product}<small>{s.volume}</small></td><td><b>{money(s.total)}</b><small>Recebido {money(s.paid)}</small></td><td><em className={s.status.toLowerCase()}>{s.status}</em></td></tr>)}</tbody></table></div>}
function Sales({sales,query,setQuery}:{sales:Sale[],query:string,setQuery:(x:string)=>void}){const f=sales.filter(s=>(s.client+s.product+s.id).toLowerCase().includes(query.toLowerCase()));return <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar cliente, produto ou pedido..."/><article className="panel"><Title h="Todos os pedidos" p={`${f.length} vendas encontradas`}/><SaleTable sales={f}/></article></>}
function Stock({products,query,setQuery}:{products:Product[],query:string,setQuery:(x:string)=>void}){const f=products.filter(p=>(p.brand+p.name).toLowerCase().includes(query.toLowerCase()));return <><section className="minis"><Mini Icon={Box} label="Itens cadastrados" val={String(products.length)}/><Mini Icon={PackagePlus} label="Volume em estoque" val={`${products.reduce((a,p)=>a+p.stock,0)} ml`}/><Mini Icon={Clock3} label="Estoque baixo" val={String(products.filter(p=>p.stock<=p.min).length)}/></section><Toolbar query={query} setQuery={setQuery} placeholder="Buscar perfume ou marca..."/><article className="panel products">{f.map(p=><div className="product" key={p.id}><i>{p.brand[0]}</i><span>{p.category}</span><h3>{p.name}</h3><p>{p.brand}</p><div className="meter"><i style={{width:`${Math.min(100,p.stock)}%`}}/></div><footer><span>Estoque<b>{p.stock} ml</b></span><span>Mínimo<b>{p.min} ml</b></span><span>Custo/ml<b>{money(p.cost)}</b></span></footer></div>)}</article></>}
function Mini({Icon,label,val}:{Icon:any,label:string,val:string}){return <div><Icon/><span>{label}<b>{val}</b></span></div>}
function Purchases(){const total=purchases.reduce((a,p)=>a+p.total,0);return <><section className="minis"><Mini Icon={ShoppingCart} label="Compras no mês" val={String(purchases.length)}/><Mini Icon={Wallet} label="Total investido" val={money(total)}/><Mini Icon={Clock3} label="Em trânsito" val={String(purchases.filter(p=>p.status==="Em trânsito").length)}/></section><article className="panel"><Title h="Histórico de compras" p="Entrada de perfumes e materiais"/><div className="table"><table><thead><tr><th>Data</th><th>Fornecedor</th><th>Item</th><th>Qtd.</th><th>Total</th><th>Status</th></tr></thead><tbody>{purchases.map((p,i)=><tr key={i}><td>{p.date}</td><td>{p.supplier}</td><td>{p.item}</td><td>{p.qty}</td><td><b>{money(p.total)}</b></td><td><em className={p.status==="Recebido"?"pago":"parcial"}>{p.status}</em></td></tr>)}</tbody></table></div></article></>}
function Clients({query,setQuery}:{query:string,setQuery:(x:string)=>void}){const f=clients.filter(c=>(c.n+c.p).toLowerCase().includes(query.toLowerCase()));return <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar cliente ou telefone..."/><article className="panel"><Title h="Base de clientes" p={`${f.length} clientes ativos`}/><div className="clients">{f.map(c=><div key={c.n}><i>{c.n.split(" ").map(x=>x[0]).slice(0,2)}</i><h3>{c.n}</h3><p>{c.p}</p><footer><span>{c.o}<small>pedidos</small></span><span>{money(c.t)}<small>compras</small></span></footer></div>)}</div></article></>}
function Finance({sales,totals}:{sales:Sale[],totals:any}){const expenses=purchases.reduce((a,p)=>a+p.total,0);return <><section className="kpis three"><Kpi label="Entradas" value={money(totals.received)} note="Recebimentos confirmados" Icon={TrendingUp} tone="green"/><Kpi label="Saídas" value={money(expenses)} note="Compras registradas" Icon={ShoppingCart} tone="orange"/><Kpi label="Resultado" value={money(totals.received-expenses)} note="Entradas menos saídas" Icon={Wallet} tone="gold"/></section><article className="panel"><Title h="Contas a receber" p="Pedidos com saldo em aberto"/><SaleTable sales={sales.filter(s=>s.status!=="Pago")}/></article></>}
function Modal({page,close,addSale,addProduct}:{page:string,close:()=>void,addSale:(s:Sale)=>void,addProduct:(p:Product)=>void}){const submit=(e:any)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(page==="stock")addProduct({id:Date.now(),brand:String(d.brand),name:String(d.name),category:String(d.category),stock:Number(d.stock),min:Number(d.min),cost:Number(d.cost)});else if(page==="sales"||page==="dashboard"||page==="finance")addSale({id:Math.floor(1000+Math.random()*8999),date:new Date().toLocaleDateString("pt-BR"),client:String(d.client),product:String(d.product),volume:String(d.volume),total:Number(d.total),paid:Number(d.paid),status:Number(d.paid)>=Number(d.total)?"Pago":Number(d.paid)>0?"Parcial":"Pendente"});else close()};return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><header><div><small>NOVO REGISTRO</small><h2>{page==="stock"?"Cadastrar produto":page==="purchases"?"Registrar compra":page==="clients"?"Cadastrar cliente":"Lançar venda"}</h2></div><button onClick={close}><X/></button></header><form onSubmit={submit}>{page==="stock"?<><Row a={["brand","Marca"]} b={["name","Perfume"]}/><Field n="category" l="Categoria"/><Row a={["stock","Estoque (ml)","number"]} b={["min","Estoque mínimo","number"]}/><Field n="cost" l="Custo por ml" type="number"/></>:page==="clients"?<><Field n="name" l="Nome completo"/><Field n="phone" l="Telefone / WhatsApp"/></>:page==="purchases"?<><Field n="supplier" l="Fornecedor"/><Field n="item" l="Item comprado"/><Row a={["qty","Quantidade","number"]} b={["total","Valor total","number"]}/></>:<><Field n="client" l="Cliente"/><Field n="product" l="Perfume"/><Field n="volume" l="Volume"/><Row a={["total","Valor total","number"]} b={["paid","Valor recebido","number"]}/></>}<footer><button type="button" onClick={close}>Cancelar</button><button className="primary">Salvar registro</button></footer></form></div></div>}
function Field({n,l,type="text"}:{n:string,l:string,type?:string}){return <label><span>{l}</span><input name={n} type={type} required step={type==="number"?"0.01":undefined}/></label>};function Row({a,b}:{a:string[],b:string[]}){return <div className="row"><Field n={a[0]} l={a[1]} type={a[2]}/><Field n={b[0]} l={b[1]} type={b[2]}/></div>}
